clear; clc; close all;

%% =========================================================
%  Plot_Exp5_RSFT_ParameterMap
%
%  从 Exp5_RSFT_ParameterMap_Data.mat 独立重绘论文 Fig. 2(a)。
%  不重新运行 SAR 成像流程。
%% =========================================================

output_dir = fullfile(pwd, "Exp5_RSFT_ParameterMap_Output");
data_path = fullfile(output_dir, "Exp5_RSFT_ParameterMap_Data.mat");

png_path = fullfile(output_dir, "Exp5_RSFT_ParameterMap.png");
pdf_path = fullfile(output_dir, "Exp5_RSFT_ParameterMap.pdf");

assert(isfile(data_path), "未找到实验数据：%s", data_path);

data = load(data_path, ...
    "range_q_list", "STR_dB_list", ...
    "f0_over_Br_list", "ssim_mean", ...
    "best_STR_dB", "best_f0_over_Br", "best_SSIM", ...
    "near_optimal_level", "near_optimal_touches_boundary", ...
    "near_optimal_delta", "total_samples");

num_R = numel(data.range_q_list);
assert(num_R == 2, "Fig. 2(a) 预期包含 R=2 和 R=3 两个子图。");

%% ==================== 统一色标 ====================
all_ssim = data.ssim_mean(:);
all_ssim = all_ssim(isfinite(all_ssim));

clim_low = local_percentile(all_ssim, 1);
clim_high = local_percentile(all_ssim, 99.5);

% 确保最优点不会被色标上界截断。
clim_high = max(clim_high, max(data.best_SSIM));

if clim_high <= clim_low
    clim_low = min(all_ssim);
    clim_high = max(all_ssim);
end

%% ==================== 绘图 ====================
fig = figure( ...
    "Color", "w", ...
    "Units", "centimeters", ...
    "Position", [2, 2, 18.2, 7.5], ...
    "Renderer", "painters");

layout = tiledlayout(fig, 1, 2, ...
    "Padding", "compact", ...
    "TileSpacing", "compact");

for r_idx = 1:num_R
    ax = nexttile(layout, r_idx);

    surface_ssim = squeeze(data.ssim_mean(r_idx, :, :));

    imagesc(ax, ...
        data.f0_over_Br_list, ...
        data.STR_dB_list, ...
        surface_ssim);

    set(ax, ...
        "YDir", "normal", ...
        "FontName", "Times New Roman", ...
        "FontSize", 8, ...
        "TickDir", "out", ...
        "Box", "on");

    axis(ax, "tight");
    clim(ax, [clim_low, clim_high]);
    hold(ax, "on");

    % 单条近最优等高线：best mean SSIM - 0.002
    [C, contour_handle] = contour(ax, ...
        data.f0_over_Br_list, ...
        data.STR_dB_list, ...
        surface_ssim, ...
        [data.near_optimal_level(r_idx), ...
         data.near_optimal_level(r_idx)], ...
        "LineColor", "w", ...
        "LineWidth", 1.5);

    if isempty(C)
        warning("R=%d 未形成可绘制的近最优等高线。", ...
            data.range_q_list(r_idx));
        contour_handle.Visible = "off";
    end

    % 全局最优点
    plot(ax, ...
        data.best_f0_over_Br(r_idx), ...
        data.best_STR_dB(r_idx), ...
        "p", ...
        "MarkerSize", 11, ...
        "MarkerFaceColor", "w", ...
        "MarkerEdgeColor", "k", ...
        "LineWidth", 1.0);

    xlabel(ax, "$f_0/B_r$", ...
        "Interpreter", "latex", ...
        "FontName", "Times New Roman", ...
        "FontSize", 9);

    ylabel(ax, "STR (dB)", ...
        "FontName", "Times New Roman", ...
        "FontSize", 9);

    title(ax, sprintf("(%c) RSFT, $R=%d$", ...
        'a' + r_idx - 1, data.range_q_list(r_idx)), ...
        "Interpreter", "latex", ...
        "FontName", "Times New Roman", ...
        "FontSize", 9, ...
        "FontWeight", "normal");

    % 在图内给出最优参数，避免正文反复查表。
    annotation_text = sprintf( ...
        "$\\mathrm{STR}^{*}=%.1f\\,\\mathrm{dB}$\n$f_0^{*}/B_r=%.2f$\n$\\mathrm{SSIM}^{*}=%.4f$", ...
        data.best_STR_dB(r_idx), ...
        data.best_f0_over_Br(r_idx), ...
        data.best_SSIM(r_idx));

    text(ax, ...
        0.03, 0.97, annotation_text, ...
        "Units", "normalized", ...
        "VerticalAlignment", "top", ...
        "HorizontalAlignment", "left", ...
        "Interpreter", "latex", ...
        "FontName", "Times New Roman", ...
        "FontSize", 7.5, ...
        "Color", "k", ...
        "BackgroundColor", "w", ...
        "Margin", 2);

    if data.near_optimal_touches_boundary(r_idx)
        warning("R=%d 的近最优区域触碰搜索边界。", ...
            data.range_q_list(r_idx));
    end
end

colormap(fig, turbo);

cb = colorbar;
cb.Layout.Tile = "east";
cb.FontName = "Times New Roman";
cb.FontSize = 8;
ylabel(cb, "Mean SSIM", ...
    "FontName", "Times New Roman", ...
    "FontSize", 9);

% 不设置总标题，便于与 Fig. 2(b) 在论文中上下组合。
exportgraphics(fig, png_path, "Resolution", 300);
exportgraphics(fig, pdf_path, "ContentType", "vector");

fprintf("Fig. 2(a) 已导出：\n");
fprintf("  PNG: %s\n", png_path);
fprintf("  PDF: %s\n", pdf_path);
fprintf("  白色等高线定义：mean SSIM >= best mean SSIM - %.4f\n", ...
    data.near_optimal_delta);
fprintf("  样本数：%d\n", data.total_samples);

%% ==================== 局部函数 ====================
function value = local_percentile(x, p)
    x = sort(x(isfinite(x)));

    if isempty(x)
        value = NaN;
        return;
    end

    position = 1 + (numel(x) - 1) * p / 100;
    lower_idx = floor(position);
    upper_idx = ceil(position);

    if lower_idx == upper_idx
        value = x(lower_idx);
    else
        value = x(lower_idx) + ...
            (x(upper_idx) - x(lower_idx)) * ...
            (position - lower_idx);
    end
end
